### PR TITLE
Add docblock type annotations to Facade

### PR DESCRIPTION
**Pull request by floristenhove**
In order to make static analysis tools understand magic methods in Facade I have added a docblock with type annotations. Laravel does this as well for its Facades.

### CODE REVIEW

**Comment by floristenhove** [comment]
@j-webb Would you be able to review this PR, please? 🙏🏻

**Comment by j-webb** [comment]
Hey @floristenhove,

Thanks for contributing. Looks good to me!

**Comment by floristenhove** [comment]
Thank you! Could you tag a new release?

**Comment by floristenhove** [comment]
@j-webb Friendly reminder, could you please tag a new release? Thank you.

**Comment by j-webb** [comment]
> @j-webb Friendly reminder, could you please tag a new release? Thank you.

@floristenhove All set - [see here](https://github.com/j-webb/laravel-unleash/releases/tag/2.4.1)

**Comment by floristenhove** [comment]
Unfortunately I don't see it being picked up by Packagist: https://packagist.org/packages/j-webb/laravel-unleash

Is there some manual action you still need to take?

**Comment by j-webb** [comment]
> Unfortunately I don't see it being picked up by Packagist: https://packagist.org/packages/j-webb/laravel-unleash
> 
> Is there some manual action you still need to take?

Ah yes, apologies. All sorted on Packagist now

**Pull request merged**
